### ISSUE TITLE
Instructions under README

### ISSUE THREAD

**Issue by marquesarthur** [FrameNetBrasil/webtool#1]
Thanks for the updated README.me folk

**config:**

I went through the instructions and I've found some errors:

```
$ cd webtool/conf
$ cp conf.dist.php conf.php
```

There is no conf under the root folder. At least, the two config files available with a find . -name \conf.dist.php are under:

```
./core/conf
./apps/webtool/conf
```

Hence, I believe that the correct path is `cd webtool/core/conf`

**database:**

The path in the readme states:  `webtool/doc/database/webtool_dump.zip`

I believe the correct path should be `webtool/apps/webtooldoc/database/webtool_dump.zip`

**running the system:**

Under the `webtool/core/conf` there is: `'startup' => 'guia'`

Which (when running the server) generated the error: 

```
Failed opening required ‘/Users/msarthur/Workspace/GSoC/webtool/apps/guia/conf/conf.php’ (include_path=‘.:’) in /Users/msarthur/Workspace/GSoC/webtool/core/classes/manager.php on line 616
```

I believe this is an error because I could neither find a folder with this name, nor it appears anywhere else other than this conf file.

**Comment by marquesarthur** [comment]
ps.: dump of the database worked without any errors :+1:

**Comment by elymatos** [comment]
Thanks @marquesarthur for the feedback!
I've updated the README file. Let me know if the issue is corrected.

**Comment by marquesarthur** [comment]
Thanks. The system is up and running. 

For reference, if anyone wants to start the system using a php server, they can run:

`php -S localhost:8000`

and access:

http://localhost:8000/index.html
