### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Ruturaj123** [FrameNetBrasil/webtool#2]
In the README, in the following line 'doc' needs to be changed to 'docs':
`⋅⋅* Restore/create the MySQL database from the dump located at webtool/apps/webtool/doc/database/webtool_dump.zip`
 to
`⋅⋅* Restore/create the MySQL database from the dump located at webtool/apps/webtool/docs/database/webtool_dump.zip`

**Comment by Sajal193** [comment]
Hi can I do this..?

**Comment by abhijain2003** [comment]
I sent a pull request related to the issue. go and checkout. This is my first issue and I would appreciate your feedback.
